FROM python:3.13.1-slim

ENV PATH="/root/.local/bin:$PATH"

RUN apt-get update && \
  apt-get install -y \
  curl \
  git

RUN curl -sSL https://install.python-poetry.org | python3 -

WORKDIR /app/python
COPY python/poetry.lock python/pyproject.toml python/poetry.toml ./
RUN poetry install

COPY . .
