name: Lint Go projects
on:
  pull_request:
    paths:
      - go/**

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}-go
  cancel-in-progress: true

jobs:
  lint-gqlgen-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go/gqlgen-server
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.22.1'
      - name: Run lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.57
          working-directory: go/gqlgen-server
