name: Format, Lint and Build Rust projects
on:
  pull_request:
    paths:
      - rust/**

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}-rust
  cancel-in-progress: true

jobs:
  ci-async-graphql-actix-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/format-lint-build-rust
        with:
          project-name: async-graphql-actix-web
