name: Format, Lint and Build all rust projects
on:
  pull_request:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}-rust
  cancel-in-progress: true

jobs:
  ci-async-graphql-actix-web:
    runs-on: ubuntu-latest
    uses: ./.github/actions/format-lint-build-rust
    with:
      project-name: async-graphql-actix-web
